run:
  timeout: 5m
  modules-download-mode: readonly

output:
  format: github-actions

linters:
  enable:
    - revive
    - errcheck
    - unused
    - staticcheck
    - ineffassign
    - govet
    - gosimple
    - bodyclose

linters-settings:
  revive:
    rules:
      - name: package-comments
        severity: warning

issues:
  exclude-use-default: false

severity:
  default-severity: error
