[tool.ruff]
exclude = [
    "diode_reconciler_sdk/reconciler",
    "diode_reconciler_sdk/validate",
]

line-length = 140

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.ruff.lint]
select = ["C", "D", "E", "F", "I", "R", "UP", "W"]
ignore = ["F401", "D100", "D203", "D212", "D400", "D401", "D404", "RET504"]
