version: '3.8'
name: diode
services:
  diode-distributor:
    image: netboxlabs/diode-distributor:${DIODE_VERSION}-${COMMIT_SHA}
    env_file: diode/env/distributor.env
    ports:
      - "8081:8081"
    depends_on:
      - diode-redis
  diode-ingester:
    image: netboxlabs/diode-ingester:${DIODE_VERSION}-${COMMIT_SHA}
    env_file: diode/env/ingester.env
    depends_on:
      - diode-redis
  diode-reconciler:
    image: netboxlabs/diode-reconciler:${DIODE_VERSION}-${COMMIT_SHA}
    env_file: diode/env/reconciler.env
    ports:
      - "8082:8081"
    depends_on:
      - diode-redis
  diode-redis:
    image: redis/redis-stack-server:latest
    command:
      - sh
      - -c
      - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD --loadmodule /opt/redis-stack/lib/rejson.so --loadmodule /opt/redis-stack/lib/redisearch.so
    env_file: diode/env/redis.env
    ports:
      - "6379:6379"
    volumes:
      - diode-redis-data:/data
  diode-redis-cli:
    image: redis/redis-stack-server:latest
    links:
      - diode-redis
    command: ./home/redis/bootstrap.sh
    env_file: diode/env/redis.env
    volumes:
      - ./diode/redis:/home/redis
volumes:
  diode-redis-data:
    driver: local
