name: Go - test
on:
  push:
    branches:
      - "!release"
  pull_request:

jobs:
  go-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: diode-server
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          check-latest: true
      - name: Run go build
        run: go build ./...
      - name: Install additional dependencies
        run: |
          go install github.com/mfridman/tparse@v0.14.0
      - name: Run go test
        run: make test-coverage
