name: Go - lint
on:
  push:
    branches:
      - "!release"
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    strategy:
      matrix:
        go: [
          "diode-sdk-go",
          "diode-server",
        ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false
      - name: golangci-lint ${{ matrix.go }}
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          working-directory: ${{ matrix.go }}
          args: --config ../.github/golangci.yaml
          skip-pkg-cache: true
          skip-build-cache: true
