name: Go - lint
on:
  push:
    branches:
      - "!release"
  pull_request:

permissions:
  contents: read

env:
  GOPRIVATE: github.com/netboxlabs/diode-sdk-go

jobs:
  golangci:
    strategy:
      matrix:
        go: [
          "diode-server",
        ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          check-latest: true
      - name: Configure git for private modules
        run: git config --global url."https://${{ secrets.ORB_CI_GH_TOKEN }}@github.com/netboxlabs".insteadOf https://github.com/netboxlabs
      - name: golangci-lint ${{ matrix.go }}
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          working-directory: ${{ matrix.go }}
          args: --config ../.github/golangci.yaml
          skip-pkg-cache: true
          skip-build-cache: true
