name: Python NetBox plugin - lint and tests
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "diode-netbox-plugin/**"
  push:
    branches:
      - "!release"
    paths:
      - "diode-netbox-plugin/**"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: docker-build-and-cache
    strategy:
      matrix:
        python-version: [ "3.10" ]
    defaults:
      run:
        working-directory: diode-netbox-plugin
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install .[dev]
          pip install .[test]
      - name: Lint with Ruff
        run: |
          ruff check --output-format=github netbox_diode_plugin/ tests/
        continue-on-error: true
      - name: Test
        run: |
          make docker-compose-netbox-plugin-test-cover
      - name: Coverage comment
        uses: orgoro/coverage@v3.2
        with:
          coverageFile: ./diode-netbox-plugin/docker/coverage/report.xml
          token: ${{ secrets.GITHUB_TOKEN }}
