name: "Python Netbox plugin - lint"
on:
  workflow_dispatch:
  push:
    branches:
      - "!release"
    paths:
      - "diode-netbox-plugin/**"

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11", "3.12" ]
    defaults:
      run:
        working-directory: diode-sdk-python
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install .[dev]
          pip install .[test]

      - name: Lint with Ruff
        run: |
          ruff --output-format=github diode-netbox-plugin/netbox_diode_plugin/ diode-netbox-plugin/tests/
        continue-on-error: true
