name: Server - release
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ release ]
    paths:
      - "diode-server/**"
env:
  GH_TOKEN: ${{ secrets.ORB_CI_GH_TOKEN }}
  SEMANTIC_RELEASE_PACKAGE: ${{ github.repository }}
  APP_DIR: diode-server

jobs:
  changed-dirs:
    name: Changed dirs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Set short SHA
        id: short-sha
        run: |
          echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
      - name: Get changed dirs
        id: get-changed-dirs
        run: |
          echo "changed-dirs<<EOF" >> $GITHUB_OUTPUT
          echo "$(git diff --name-only --diff-filter=ACMRTUXB origin/${{ github.base_ref }} ${{ steps.short-sha.outputs.short_sha }} | xargs dirname | sort -u)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Echo changed dirs
        run: |
          echo "changed-dirs: ${{ steps.get-changed-dirs.outputs.changed-dirs }}"
